insert into genres (name)
values ('Pop'),
       ('Rock'),
       ('Rap'),
       ('Ska'),
       ('Indie'),
       ('Classic metal'),
       ('Dance music');

insert into artist (name, picture_url)
values ('Макс Корж', 'maks_korzh.jpg'),
       ('Ляпис Трубецкой', 'lyapis_trubeckoj.jpg'),
       ('Агата Кристи', 'agata_kristi.jpg'),
       ('Billie Eilish', 'billie_eilish.jpg'),
       ('Elvis Presley', 'elvis_presley.jpg'),
       ('Ария', 'ariya.jpg'),
       ('Наутилус Помпилиус', 'nautilus_pompilius.jpg'),
       ('Кипелов', 'kipelov.jpg'),
       ('Little Big', 'little_big.jpg'),
       ('Океан Ельзи', 'okean_elzi.jpg'),
       ('Noize MC', 'noize_mc.jpg');

insert into album (name, release_date, artist_id, picture_url)
values ('2 типа людей', '2019-08-22', 1, '2_tipa_lyudej.jfif'),
       ('Жить в кайф', '2013-10-20', 1, 'zhit_v_kajf.jfif'),
       ('Матрёшка', '2014-03-01', 2, 'matryoshka.jfif'),
       ('Весёлые картинки', '2013-03-14', 2, 'vesyolye_kartinki.jfif'),
       ('Ностальгия', '2011-07-05', 3, 'nostalgiya.jfif'),
       ('Эпилог', '2010-07-10', 3, 'epilog.jfif'),
       ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', '2019-03-29', 4, 'when_we_all_fall_asleep_where_do_we_go.jfif'),
       ('Devil In Disguise', '1963-07-01', 5, 'devil_in_disguise.jfif'),
       ('2000 и одна ночь', '1999-12-15', 6, '2000_i_odna_noch.jfif'),
       ('Золотой век', '2015-12-18', 7, 'zolotoj_vek.jfif'),
       ('Вавилон', '2010-07-10', 8, 'vavilon.jfif'),
       ('UNO', '2020-03-13', 9, 'uno.jfif'),
       ('Antipositive, Pt.1', '2018-05-08', 9, 'antipositive_pt_1.jfif'),
       ('Gloria', '2005-09-22', 10, 'gloria.jfif'),
       ('Янанебiбув', '2000-02-21', 10, 'yananebibuv.jfif'),
       ('Последний Альбом', '2010-05-28', 11, 'pslednij_albom.jfif');

insert into songs(name, genre_id, album_id, is_cover, url)
values ('2 типа людей', 3, 1, 0, 'МаксКорж-2типалюдей.mp3'),
       ('Жить в Кайф', 3, 2, 0, 'МаксКорж-ЖитьвКайф.mp3'),
       ('Эндорфин', 3, 2, 0, 'МаксКорж-Эндорфин.mp3'),
       ('Танцуй!', 4, 3, 0, 'ЛяписТрубецкой-Танцуй!.mp3'),
       ('Воины света', 4, 3, 0, 'ЛяписТрубецкой-Воинысвета.mp3'),
       ('Я верю', 4, 4, 0, 'ЛяписТрубецкой-Яверю.mp3'),
       ('Грай', 4, 4, 0, 'ЛяписТрубецкой-Грай.mp3'),
       ('Как на войне', 2, 5, 0, 'АгатаКристи-Какнавойне.mp3'),
       ('В такси', 2, 6, 0, 'АгатаКристи-Втакси.mp3'),
       ('Bad guy', 5, 7, 0, 'BillieEilish-badguy.mp3'),
       ('Bury a friend', 5, 7, 0, 'BillieEilish-buryafriend.mp3'),
       ('You should see me in a crown', 5, 7, 0, 'BillieEilish-youshouldseemeinacrown.mp3'),
       ('Devil in Disguise', 2, 8, 0, 'ElvisPresley-DevilinDisguise.mp3'),
       ('Улица роз', 6, 9, 0, 'Ария-Улицароз.mp3'),
       ('Скованные одной цепью', 2, 10, 0, 'НаутилусПомпилиус-Скованныеоднойцепью.mp3'),
       ('Я свободен', 6, 11, 0, 'Кипелов-Ясвободен.mp3'),
       ('Uno', 7, 12, 0, 'Littlebig-uno.mp3'),
       ('Faradenza', 7, 13, 0, 'LittleBig-Faradenza.mp3'),
       ('Без Бою', 2, 14, 0, 'ОкеанЕльзи-БезБою.mp3'),
       ('Ти i я', 2, 14, 0, 'ОкеанЕльзи-Тиiя.mp3'),
       ('Фiалки', 2, 15, 0, 'ОкеанЕльзи-Фiалки.mp3'),
       ('Сосни', 2, 15, 0, 'ОкеанЕльзи-Сосни.mp3'),
       ('Устрой дестрой', 3, 16, 0, 'NoizeMC-Устройдестрой.mp3');

insert into song_artist
values (1, 1),
       (2, 1),
       (3, 1),
       (4, 2),
       (5, 2),
       (6, 2),
       (7, 2),
       (8, 3),
       (9, 3),
       (10, 4),
       (11, 4),
       (12, 4),
       (13, 5),
       (14, 6),
       (15, 7),
       (16, 8),
       (17, 9),
       (18, 9),
       (19, 10),
       (20, 10),
       (21, 10),
       (22, 10),
       (23, 11);