export enum ConstantsEnum {
  backURL = "http://localhost:3000/",
  album = "album/",
  images = "images/",
  songs = "songs/",
  searchURL = "search",
  registrationURL = "registration",
  loginURL = "login",
  userAPIURL = "user/",
  playlistAPIURL = "playlist/",
  getPlaylists = "getplaylists",
  createPlaylist = "createplaylist",
  addSongToPlaylist = "addsongtoplaylist",
  uploadFile = "upload",
  uploads = "uploads/",
  genres = "genres",
  getSongsByGenreId = "getsongsbygenreid/",
  getArtistInfoById = "artist/",
  getRecommendations = "recommendations",
}
